### ISSUE TITLE
only Loading...

### ISSUE THREAD

**Issue by lebsral** [asadsahi/ng2fb-bootstrap#1]
Live site at 
https://ng2fb-bootstrap.firebaseapp.com/
just says "Loading..."

**Comment by asadsahi** [comment]
@lebsral production build is broken since I have upgraded to RC6 and latest version of angular cli.. I have an issue opened with them. As soon as it is resolved, I will get it up and running again. Have and issue with CLI guys: [#2007](https://github.com/angular/angular-cli/issues/2007)

**Comment by asadsahi** [comment]
I have turned off production and scripts are unminified becuase of cli issue. which has updated the demo.  Closing it for now.
